import Head from "next/head";
import Greetings from "../../components/GreetingsComponent";
import Header from "../../components/HeaderComponent";
import GoBack from "../../components/common/GoBackComponent";

const ABHIJEET = {
  fName: "Abhijeet",
  lName: "Salve",
  skills: ["design", "code", "sing", "play guitar"],
  shortIntro:
    "I'm a full stack frontend developer who likes to build seamless and beautiful user experiences\nby harnessing my development and design skills.",
  calendyUserName: "abhijeetsalve",
  socialLinks: [
    {
      name: "linkedIn",
      url: "https://in.linkedin.com/in/abhijeet-salve-25850a84",
      isActive: true,
    },
    {
      name: "dribble",
      url: "https://dribbble.com/_abhijeetsalve",
      isActive: true,
    },
    {
      name: "twitter",
      url: "https://twitter.com/_abhijeetsalve",
      isActive: true,
    },
    {
      name: "youtube",
      url: "https://www.youtube.com/channel/UCUjeh9W8J8LHP1qWcsCGNqA",
      isActive: true,
    },
    {
      name: "instagram",
      url: "https://www.instagram.com/abhijeet.sol/",
      isActive: true,
    },
  ],
  technicalSkills: [
    "ReactJs",
    "React Native",
    "NextJs",
    "Strapi",
    "Redux",
    "Apollo GraphQL",
    "REST API Integrations",
    "Solana web3.js ",
    "Design System",
    "Wireframing",
    "Figma",
    "tailwind css",
    "CSS3",
    "SaSS",
    "JavaScript",
    "HTML5",
  ],
};

export default function Abhijeet() {
  return (
    <>
      <Head>
        <title>
          {ABHIJEET.fName} {ABHIJEET.lName}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header user={ABHIJEET} />
      <GoBack />
      {/* <MainSkills skills={user?.technicalSkills} /> */}

      <Greetings user={ABHIJEET} />
    </>
  );
}
