import Head from "next/head";
import Greetings from "../../components/GreetingsComponent";
import MainSkills from "../../components/MainSkillsComponent";
import Header from "../../components/HeaderComponent";
import GoBack from "../../components/common/GoBackComponent";

const KARISHMA = {
  fName: "Karishma",
  lName: "Baat",
  skills: ["hire", "research", "read", "doodle"],
  shortIntro:
    "I am an HR professional who likes to solve human capital issues & the kick of finding the\nright person for the right job.",
  calendyUserName: "curryshma",
  socialLinks: [
    {
      name: "linkedIn",
      url: "https://www.linkedin.com/in/karishmabaat/",
      isActive: true,
    },
    {
      name: "twitter",
      url: "https://twitter.com/curry_shma",
      isActive: true,
    },
    {
      name: "instagram",
      url: "https://www.instagram.com/curry.shma/",
      isActive: true,
    },
  ],
};

export default function Karishma() {
  return (
    <>
      <Head>
        <title>
          {KARISHMA.fName} {KARISHMA.lName}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header user={KARISHMA} />
      <GoBack />
      {/* <MainSkills skills={user?.technicalSkills} /> */}

      <Greetings user={KARISHMA} />
    </>
  );
}
