// import { useEffect, useCallback } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Greetings from "../components/GreetingsComponent";
import { getUserDetails } from "../userUtils";
// import { fetchAPI } from "../utils/fetch-api";

const Profile = () => {
  const router = useRouter();
  const { user } = router.query;

  const userDetails = getUserDetails(user);

  // const fetchData = useCallback(async (start, limit) => {
  //   const token = process.env.NEXT_PUBLIC_STRAPI_API_TOKEN;
  //   const path = `/stars`;

  //   const options = { headers: { Authorization: `Bearer ${token}` } };
  //   const responseData = await fetchAPI(path, options);
  //   console.log("...", responseData);
  // }, []);

  // useEffect(() => {
  //   fetchData();
  // });

  return (
    <>
      <Head>
        <title>
          {userDetails.fName} {userDetails.lName}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      {/* <MainSkills technicalSkills={userDetails?.technicalSkills} /> */}

      <Greetings user={userDetails} />
    </>
  );
};

export default Profile;
